name: "upload-to-cdn"

on:
  push:
    branches:
      - "main"
      - "dev-*"

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-node@v3"
        with:
          node-version: "16"
          cache: "npm"
      - name: "Install dependencies"
        run: "npm ci"
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
      - name: "Build application"
        run: "npm run build"
      - name: dev-upload
        uses: nais/frontend-plattform-cdn-upload-action@main
        with:
          cdn-environment: cdn.dev.nav.no
          cdn-team-name: min-side
          cache-invalidation: true
          source: ./dist/tms-utkast-mikrofrontend.js
          destination: "tms-utkast-mikrofrontend"

      - name: prod-upload
        if: github.ref == 'refs/heads/main'
        uses: nais/frontend-plattform-cdn-upload-action@main
        with:
          cdn-environment: cdn.nav.no
          cdn-team-name: min-side
          cache-invalidation: true
          source: ./dist/tms-utkast-mikrofrontend.js
          destination: "tms-utkast-mikrofrontend"
